[default]

[default.data.raw]
raw_sentence_data = "raw/coding_test_sentence_data.txt"
raw_test_data = "mapping/coding_test_toy_set_acronyms.csv"

[default.data.mapping]
mapping_data = "mapping/coding_test_toy_set_acronyms.csv"
mapping_columns = ["acronym", "expansion"]

[default.data.training]
dataset = "training/sentence_data_2022_03_05.csv"

[default.data.test]
dataset = "test/test_sentence_data_2022_03_05.csv"

[default.pipeline.preprocessing]
val_split_percentage = 0.2

[default.pipeline.vectorizer]
vocab_size = 20000
sequence_length = 30
batch_size = 8
decoded_sequence_length = 30
input_vectorizer_path = 'model_artifact/input_vectorizer.pkl'
output_vectorizer_path = 'model_artifact/output_vectorizer.pkl'

[default.pipeline.transformer]
epochs = 30
dropout_percentage = 0.5
embedding_dim = 128
latent_dim = 2048
num_heads = 8

[default.pipeline]
pipeline_artifacts_path = "model_artifact"
model_artifact = "model_artifact.pkl"
model_weights = "model_weights.h5"

[default.api]
version = "0.1.0"

[default.mlflow]
tracking_uri = "http://host.docker.internal:5000" # change to localhost when running locally
